### ISSUE TITLE
Can't deplogy on my server.

### ISSUE THREAD

**Issue by beautiful-boyyy** [replicate/scribble-diffusion#42]
<img width="1378" alt="Screenshot 2023-03-08 at 14 51 55" src="https://user-images.githubusercontent.com/66351806/223640439-e43df133-beb6-4253-8916-4b004e68f1c6.png">

**Comment by lasan90** [comment]
In https://upload.io/dashboard/files copy UPLOAD_IO_ACCOUNT_ID and UPLOAD_IO_PUBLIC_API_KEY, and change this in your local proyect.
