### ISSUE TITLE
Only allowing about 10 minutes of use

### ISSUE THREAD

**Issue by jsholdingford** [replicate/scribble-diffusion#51]
We are using Scribblediffusion.com with elementary school students in a computer lab setting.  The first group was able to play for about 10 minutes before the waiting bubbles just continue without creating an image.  The next group ran into the waiting bubbles immediately upon trying their first image.  This has been consistent over 2 days of class.

Is there a limit to the amount of time a particular device can access the site?

**Comment by jsholdingford** [comment]
No, we have not continued using it in a whole class environment.  Some
students have elected to use it on occasion and they do not run into issues.

Thank you,

Jennifer Sandstrom

Holdingford Public Schools
Learning & Mobile Technology Support
Co-District Assessment Coordinator (DAC)
320-746-4414

***@***.***>

**Comment by zeke** [comment]
Thanks for the reply. Moving forward, feel free to use the site as much as you like. The limitation you were experiencing is not imposed by the site.
