### ISSUE TITLE
error API request failed: Unprocessable Entity

### ISSUE THREAD

**Issue by OhJunSol** [replicate/scribble-diffusion#68]
It was executed in the M1 environment. I proceeded as written in the ReadMe file.
When I press the Go Button in , the following error occurs.

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- info Loaded env from /Users/ojunsol/development/scribble-diffusion/.env.local
- event compiled client and server successfully in 392 ms (205 modules)
- wait compiling...
- event compiled client and server successfully in 215 ms (205 modules)
- wait compiling / (client and server)...
- event compiled client and server successfully in 325 ms (1134 modules)
- wait compiling /api/predictions (client and server)...
- event compiled successfully in 75 ms (65 modules)
- wait compiling /_error (client and server)...
- error node_modules/replicate/index.js (162:12) @ Replicate.request
- error API request failed: Unprocessable Entity
null

**Comment by X-Matrix2018** [comment]
i have this problem too :((

**Comment by zhaxiu3** [comment]
me too

**Comment by zeke** [comment]
Sorry about that, y'all. I've got a fix in the works here: https://github.com/replicate/scribble-diffusion/pull/74
