### ISSUE TITLE
Invalid webhook URL

### ISSUE THREAD

**Issue by maoyanfei** [replicate/scribble-diffusion#85]
- error node_modules\replicate\lib\predictions.js (20:12) @ Replicate.createPrediction
- error Invalid webhook URL
null

**Comment by maoyanfei** [comment]
Solved

**Comment by vectris-dev** [comment]
Not sure why @maoyanfei didn't add this, but for others experiencing this error it occurs when running locally without NGROK setup. Replicate uses webhooks so you need NGROK setup to run locally and to add NGROK_HOST as specified in .env.example

**Comment by helloWorldxj** [comment]
> Solved
How was the problem solved?

**Comment by vectris-dev** [comment]
> > Solved
> > How was the problem solved?

Add NGROK_HOST as specified in .env.example

**Comment by helloWorldxj** [comment]
![QQ截图20241229190039](https://github.com/user-attachments/assets/9a84b467-e27d-40d1-a792-68c727272682)
Thank you. I also want to ask if you finally ran it. After solving this problem, I found that there were still some functions undefined in the code. Did you encounter this problem at that time? Thank you again for taking the time to reply to me!!

**Comment by vectris-dev** [comment]
> ![QQ截图20241229190039](https://private-user-images.githubusercontent.com/104408846/399250989-9a84b467-e27d-40d1-a792-68c727272682.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1OTI0MDAsIm5iZiI6MTczNTU5MjEwMCwicGF0aCI6Ii8xMDQ0MDg4NDYvMzk5MjUwOTg5LTlhODRiNDY3LWUyN2QtNDBkMS1hNzkyLTY4YzcyNzI3MjY4Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMFQyMDU1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTg0MjNhZTFkNDU5ZjcyNGE2ZDViYWEwNzUyZjA0ZmJmZjY1YTNjNzQ3YTkyODZhYWE1YWY0YWM3MTg5MjAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jUQvpjsW99Qhzw-fN9kfVDnkvMY0WMGP8MUjpdm5uk8) Thank you. I also want to ask if you finally ran it. After solving this problem, I found that there were still some functions undefined in the code. Did you encounter this problem at that time? Thank you again for taking the time to reply to me!!

Hi, yes I have it deployed and running well. I'd recommend you raise a seperate issue and tag me in order to keep this issue on topic (also before you do, make you sure you `npm install`)
